name: Publish to Dev

on:
    workflow_dispatch:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout [test-prod]
              uses: actions/checkout@v4
              with:
                repository: 'matikin9/test-prod'
                ref: 'dev'
                path: 'test-prod'
            - name: Checkout [test-dev]
              uses: actions/checkout@v4
              with:
                repository: 'matikin9/test-dev'
                ref: 'dev'
                path: 'test-dev'
            - name: 'Copy files'
              run: |
                  echo "Publishing to Dev"
                  cp -r test-prod/* test-dev/
                  cd test-dev
            - name: 'Commit and push changes'
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: '[Auto] Publish to Dev'
            
            